### ISSUE TITLE
Hope this doesnt happen to you to...

### ISSUE THREAD

**Issue by PAEz** [yikuansun/photopealoader#4]
https://github.com/DUOLabs333/photopea/issues/19

**Comment by yikuansun** [comment]
Don't think it will, since the creator, not I, gets money from the ad revenue when people use this app.

Edit: part of the Photopea API was designed around embedding Photopea, which is what we're doing.

**Comment by PAEz** [comment]
You get ads?  I dont, I get one of these two......
![Untitled](https://user-images.githubusercontent.com/785449/159850586-69ead3bf-d035-4a86-a3ba-6a05016b98d0.jpg)
![Untitled2](https://user-images.githubusercontent.com/785449/159850614-0cee4d72-affb-4770-9e95-f8e7c9834002.jpg)

**Comment by yikuansun** [comment]
@PAEz Shoot, I'm not sure... but I certainly didn't write in any adblocking code...

**Comment by yikuansun** [comment]
@PAEz Got one
![image](https://user-images.githubusercontent.com/38194363/164794472-1d6405e1-8343-4c07-a616-eca63044e312.png)
